// Client exports (keep existing)
export { createClient, createBrowserClient, createServerClient } from './clients'
// Type exports
export type { LifePillar, Goal, Task, FailureCost, TaskAssignee } from './types'
// Query helpers
export { getPillars, getPillarsWithProgress } from './pillars'
export type { PillarWithProgress } from './pillars'
export { createPillar, updatePillar, deletePillar } from './pillars-mutations'
export type { CreatePillarInput } from './pillars-mutations'
export { getGoals, createGoal, updateGoal, deleteGoal, getGoalsWithProgress } from './goals'
export type { CreateGoalInput, GoalWithProgress } from './goals'
export { getTasksByGoal, createTask, updateTask, deleteTask, unpinOneThingForUser } from './tasks'
export type { CreateTaskInput } from './tasks'
export { getOneThingTask, getTasksForQueue } from './tasks-scoring'
export { getTasksWithDeadlines, getTasksByGoalWithContext } from './tasks-context'
export type { TaskWithContext } from './tasks-context'
export { getAllTasksWithContext } from './tasks-all'
export { saveAssessment, getAssessmentHistory, getLatestAssessment, deleteAssessment } from './assessments'
export type { Assessment, DomainKey, DomainScores, DomainAverages } from './assessments'
export { getTreeData } from './tree'
export type { TreeData } from './tree'
